# This is the configuration used to check the rubocop source code.
# See https://github.com/bbatsov/rubocop/blob/master/config/default.yml for info

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
  RunRailsCops: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
