require "spree/testing_support/authorization_helpers"
require "spree/testing_support/capybara_ext"
require "spree/testing_support/controller_requests"
require "spree/testing_support/factories"
require "spree/testing_support/flash"
require "spree/testing_support/preferences"
require "spree/testing_support/url_helpers"
